[build-system]
requires = ["setuptools>=65.5.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyleetcode-cli"
version = "0.1.0"
authors = [
  { name="Jakub Kubiak", email="jakubkubiak234@gmail.com" },
]
description = "A CLI tool to access leetcode questions."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Coderbeep/LeetCode-CLI"
"Bug Tracker" = "https://github.com/Coderbeep/LeetCode-CLI/issues"